import Sidebar from "@/components/providers/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Wallet",
  description: "Generated by create next app",
};

export default function WalletLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='flex gap-2 p-5 h-screen'>
      <Sidebar />
      <section className='flex-1 bg-primary-foreground rounded-md py-6 px-20'>
        {children}
      </section>
    </main>
  );
}
